#!/usr/bin/env python3
"""
Scans ~/Desktop/saskaitos/2026 for new invoice PDFs
and updates data-import.js so the dashboard picks them up.
Run by double-clicking sync-invoices.command
"""

import os, re, json, subprocess
from datetime import datetime

INVOICE_FOLDER = os.path.expanduser("~/Desktop/saskaitos/2026")
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
IMPORT_FILE = os.path.join(SCRIPT_DIR, "data-import.js")

MONTHS_LT = {
    'sausio': 1, 'vasario': 2, 'kovo': 3, 'balandžio': 4,
    'gegužės': 5, 'birželio': 6, 'liepos': 7, 'rugpjūčio': 8,
    'rugsėjo': 9, 'spalio': 10, 'lapkričio': 11, 'gruodžio': 12
}

def extract_text(pdf_path):
    # Try pdftotext (best, available if Homebrew poppler is installed)
    try:
        r = subprocess.run(['pdftotext', pdf_path, '-'],
                           capture_output=True, text=True, timeout=10)
        if r.stdout.strip():
            return r.stdout
    except Exception:
        pass
    # Fall back to strings (always available on macOS)
    try:
        r = subprocess.run(['strings', pdf_path],
                           capture_output=True, text=True, timeout=10)
        if r.stdout.strip():
            return r.stdout
    except Exception:
        pass
    return ''

def parse_invoice(text, filename):
    # Invoice number from filename e.g. "26-01"
    nr_match = re.search(r'(26-\d+)', filename)
    inv_nr = nr_match.group(1) if nr_match else ''

    # Date from PDF text e.g. "2026 m. sausio 5 d."
    date_match = re.search(r'(\d{4})\s*m\.\s*(\w+)\s*(\d+)\s*d\.', text)
    inv_date = ''
    if date_match:
        year = date_match.group(1)
        month_lt = date_match.group(2).lower()
        day = date_match.group(3)
        month_num = MONTHS_LT.get(month_lt, 1)
        inv_date = f'{year}-{month_num:02d}-{int(day):02d}'

    # Total amount — last euro value in file
    amounts = re.findall(r'[€E]\s*([\d\s]+[,.][\d]{2})', text)
    total = 0
    if amounts:
        raw = amounts[-1].strip().replace('\xa0', '').replace(' ', '').replace(',', '.')
        try:
            total = float(raw)
        except Exception:
            pass

    # Client name from filename
    # Pattern: 26-XX - saskaita - CLIENT NAME - YYYY-MM-DD.pdf
    client_match = re.search(r'\d+ - saskaita - (.+?) - \d{4}', filename)
    client_name = client_match.group(1).strip() if client_match else ''

    # Detect if preliminary invoice (skip — final invoice has same number)
    is_preliminary = '_2' not in filename and 'Išankstinė' in text

    return {
        'id': 'pdf_' + inv_nr.replace('-', '_'),
        'title': f'Nr. {inv_nr}',
        'clientName': client_name,
        'amount': total,
        'dueDate': inv_date,
        'status': 'sent',
        'paidAt': None,
        'createdAt': inv_date + 'T00:00:00.000Z' if inv_date else datetime.now().isoformat(),
        'preliminary': is_preliminary
    }

def main():
    if not os.path.isdir(INVOICE_FOLDER):
        print(f"Folder not found: {INVOICE_FOLDER}")
        return

    # Only process final invoices (skip _2 duplicates which are preliminary versions)
    pdfs = sorted([
        f for f in os.listdir(INVOICE_FOLDER)
        if f.lower().endswith('.pdf') and not f.endswith('_2.pdf')
    ])

    invoices = []
    clients_seen = {}

    for pdf in pdfs:
        path = os.path.join(INVOICE_FOLDER, pdf)
        text = extract_text(path)
        inv = parse_invoice(text, pdf)
        if not inv['id']:
            continue
        # Skip preliminary — we already have the final version
        if inv.get('preliminary'):
            continue
        invoices.append(inv)
        cname = inv['clientName']
        if cname and cname not in clients_seen:
            safe_id = re.sub(r'[^a-z0-9]', '_', cname.lower())
            clients_seen[cname] = {
                'id': f'pdf_c_{safe_id}',
                'name': cname,
                'type': 'agency',
                'email': '',
                'notes': '',
                'createdAt': '2026-01-01T00:00:00.000Z'
            }

    invoices_json = json.dumps(invoices, ensure_ascii=False, indent=2)
    clients_json = json.dumps(list(clients_seen.values()), ensure_ascii=False, indent=2)

    js = f"""// Auto-generated by sync-invoices.py on {datetime.now().strftime('%Y-%m-%d %H:%M')} — do not edit manually
(function () {{
    var newInvoices = {invoices_json};
    var newClients  = {clients_json};

    // ── Merge clients ───────────────────────────────────────────
    var existingClients = JSON.parse(localStorage.getItem('studio_clients') || '[]');
    newClients.forEach(function (c) {{
        if (!existingClients.find(function (e) {{ return e.name === c.name; }})) {{
            existingClients.push(c);
        }}
    }});
    localStorage.setItem('studio_clients', JSON.stringify(existingClients));

    // ── Merge invoices ──────────────────────────────────────────
    var existingInv = JSON.parse(localStorage.getItem('studio_invoices') || '[]');
    newInvoices.forEach(function (inv) {{
        var clients = JSON.parse(localStorage.getItem('studio_clients') || '[]');
        var client  = clients.find(function (c) {{ return c.name === inv.clientName; }});
        inv.clientId = client ? client.id : '';
        delete inv.clientName;
        delete inv.preliminary;
        if (!existingInv.find(function (e) {{ return e.id === inv.id; }})) {{
            existingInv.push(inv);
            console.log('Added invoice:', inv.title);
        }}
    }});
    localStorage.setItem('studio_invoices', JSON.stringify(existingInv));
}})();
"""

    with open(IMPORT_FILE, 'w', encoding='utf-8') as f:
        f.write(js)

    print(f"\n✓  Found {len(pdfs)} PDFs in saskaitos/2026")
    print(f"✓  Synced {len(invoices)} invoices → data-import.js")
    print(f"\n→  Refresh dashboard.html in Safari to see new invoices.\n")

if __name__ == '__main__':
    main()
